import {
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  BeakerIcon,
  BookOpenIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  ChartBarSquareIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  FunnelIcon,
  HeartIcon,
  HomeIcon,
  IdentificationIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  NoSymbolIcon,
  PencilSquareIcon,
  PhoneIcon,
  PrinterIcon,
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Squares2X2Icon,
  UserCircleIcon,
  UserGroupIcon,
  UsersIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';
import { Bars3Icon } from '@heroicons/react/24/solid';

const icons = {
  heartPulse: HeartIcon,
  shield: ShieldCheckIcon,
  calendar: CalendarDaysIcon,
  users: UsersIcon,
  capsule: ClipboardDocumentListIcon,
  flask: BeakerIcon,
  clock: ClockIcon,
  arrowRight: ArrowRightIcon,
  arrowLeft: ArrowLeftIcon,
  spark: SparklesIcon,
  userCircle: UserCircleIcon,
  logout: ArrowRightIcon,
  menu: Bars3Icon,
  close: XMarkIcon,
  check: CheckCircleIcon,
  checkBadge: CheckBadgeIcon,
  building: BuildingOffice2Icon,
  home: HomeIcon,
  book: BookOpenIcon,
  records: ClipboardDocumentListIcon,
  prescriptions: ClipboardDocumentListIcon,
  dashboard: Squares2X2Icon,
  search: MagnifyingGlassIcon,
  filter: FunnelIcon,
  warning: ExclamationTriangleIcon,
  info: InformationCircleIcon,
  print: PrinterIcon,
  download: ArrowDownTrayIcon,
  edit: PencilSquareIcon,
  swap: ArrowPathIcon,
  group: UserGroupIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronDown: ChevronDownIcon,
  question: QuestionMarkCircleIcon,
  profile: IdentificationIcon,
  phone: PhoneIcon,
  eye: EyeIcon,
  ban: NoSymbolIcon,
  analytics: ChartBarSquareIcon,
};

export default function AppIcon({ name, className = 'h-5 w-5' }) {
  const Icon = icons[name] || SparklesIcon;
  return <Icon className={className} aria-hidden="true" />;
}
